name: Run API Tests

on:
  workflow_dispatch:  # Позволяет запускать вручную через GitHub Actions
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          echo "STAGE is set to: $STAGE"
          echo "API-TOK is set: [${{ secrets.API-TOK != '' }}]"  # Проверяем, передан ли токен
        env:
          STAGE: prod
          API-TOK: ${{ secrets.API-TOK }}

      - name: Run API tests
        env:
          STAGE: prod
          API-TOK: ${{ secrets.API-TOK }}
        run: |
          pytest --alluredir=allure-results
        

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          publish_dir: allure-history
