name: Run API Tests

on:
  workflow_dispatch:  # Позволяет запускать вручную через GitHub Actions
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Restore Allure history
        uses: actions/cache@v3
        with:
          path: allure-history
          key: allure-history-${{ github.run_id }}
          restore-keys: allure-history-

      - name: Run API tests
        run: |
          STAGE=prod pytest --alluredir=allure-results
        env:
          API_TOK: ${{ secrets.API_TOK }}
        continue-on-error: true

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Copy Allure history
        run: |
          mkdir -p allure-history
          cp -r allure-report/history allure-history/ || echo "No previous history"

      - name: Deploy Allure report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          publish_dir: allure-history
